version: 2.1
jobs:
  compile:
   docker:
      - image: fadlyas/kernel_dockerfile:latest
   resource_class : 2xlarge
   steps:
      - run:
          command: |
           git clone https://github.com/akhilnarang/scripts
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
