version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           git clone https://github.com/akhilnarang/scripts
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
